### Topics ###

![](2023-08-04-20-39-03.png)

In [11]:
import numpy as np
print(np.__version__)

a = np.array([1,2,4])
print(f'a: {a}')
print(f'shape: {a.shape}')
print(f'dtype: {a.dtype}')
print(f'no. of dim: {a.ndim}')
print(f'no. of elements: {a.size}')
print(f'size of each item: {a.itemsize}')

1.22.3
a: [1 2 4]
shape: (3,)
dtype: int32
no. of dim: 1
no. of elements: 3
size of each item: 4


## Arrays vs Lists ##

### Data Type: ###
* Lists: A list in Python is a collection of heterogeneous data types. This means you can have elements of different types (e.g., integers, strings, floats) within the same list.
* Arrays: In Python, arrays are implemented through the NumPy library. Arrays are homogeneous, meaning all elements in the array must have the same data type (e.g., int, float, etc.).

### Functionality and Operations: ###
* Lists: Python lists come with a wide range of built-in methods for manipulation, such as `append(), pop(), extend()`, etc. They are versatile and flexible but may not be as efficient for numerical computations.
* Arrays: Numpy arrays offer a variety of numerical operations that can be performed on the entire array efficiently due to their homogeneous nature. These operations include element-wise arithmetic, broadcasting, matrix multiplication, and more.

### Performance: ###
* Lists: Python lists are generally slower for numerical computations and large-scale data manipulation due to their dynamic nature and lack of vectorization.
* Arrays: Numpy arrays are optimized for numerical computations and are significantly faster for large datasets, especially when using vectorized operations.

### Memory Overhead: ###
* Lists: Python lists have more memory overhead compared to arrays due to additional information they store, such as the type of each element and the reference count.
* Arrays: Numpy arrays have less memory overhead because they store data more compactly in contiguous blocks of memory.

In [16]:
# Dot product #
a = np.array([1,2,3])
b = np.array([4,9,8])

# method 1
dot = (a * b).sum()
print(dot)

# method 2
print(np.dot(a,b))

# method 3
dot1 = a @ b
print(dot1)

46
46
46


In [42]:
# MULTIDIMENSIONAL ARRAYS #

mArr = np.array([[1,3], [4,7]])
print(mArr)
print(mArr.shape)
print(mArr[0,1])

# retrieve all the rows in column 0
print(f'retrieve all the rows in column 0:\n {mArr[:,0]}')
# retrieve all the coulmn in row 0
print(f'retrieve all the coulmn in row 0:\n {mArr[0,:]}')

# transpose
print(f'transpose:\n{mArr.T}')

# determinant
print(f'determinant:\n{np.linalg.det(mArr)}')

# inverse
print(f'inverse:\n{np.linalg.inv(mArr)}')   # the array should be a square one

# bool indexing
a1 = np.array([[1,4], [3,2], [6,9], [5,0]])
bool_idx = a1>4
print(f'bool array: {bool_idx}')
print(f'value array: {a1[a1>4]}')

# modifying array based on certain condition
b1 = np.where(a1>2, a1, -1)
print(f'modified array: {b1}')

# fancy indexing
c1 = np.array([32,54,23,74,34,87])
c2 = np.argwhere(c1%2 == 0).flatten()    # index array  # .flatten() - suppresses the array to 1D
print(f'fancy indexing: {c1[c2]}')



[[1 3]
 [4 7]]
(2, 2)
3
retrieve all the rows in column 0:
 [1 4]
retrieve all the coulmn in row 0:
 [1 3]
transpose:
[[1 4]
 [3 7]]
determinant:
-4.999999999999999
inverse:
[[-1.4  0.6]
 [ 0.8 -0.2]]
bool array: [[False False]
 [False False]
 [ True  True]
 [ True False]]
value array: [6 9 5]
modified array: [[-1  4]
 [ 3 -1]
 [ 6  9]
 [ 5 -1]]
fancy indexing: [32 54 74 34]


In [44]:
# reshaping

a2 = np.array([2,6,3,7,5,9])
a2.reshape(3,2)
#a2.reshape(2,4) # ERROR

array([[2, 6],
       [3, 7],
       [5, 9]])