<a href="https://colab.research.google.com/github/bhuvanbharath/notes/blob/main/DeepLearning_in_CV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import tensorflow as tf

## Tensor in Numbers

In [ ]:
tensor_1d = tf.constant([2,4,9])
print(tensor_1d)

tensor_2d = tf.constant([[2,4,5], [3,6,9]])
print(tensor_2d)

tensor_3d = tf.constant([[[4,8,7], [8,0,2]], [[4,8,7], [8,0,2]], [[4,8,7], [8,0,2]]])
print(tensor_3d)

tf.Tensor([2 4 9], shape=(3,), dtype=int32)
tf.Tensor(
[[2 4 5]
 [3 6 9]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[[4 8 7]
  [8 0 2]]

 [[4 8 7]
  [8 0 2]]

 [[4 8 7]
  [8 0 2]]], shape=(3, 2, 3), dtype=int32)


## Tensor in Strings

In [ ]:
tensor_str = tf.constant("tensor string here")
print(tensor_str)
tensor_str_list = tf.constant([["tensor"],["string"], ["here"]])
print(tensor_str_list)

tf.Tensor(b'tensor string here', shape=(), dtype=string)
tf.Tensor(
[[b'tensor']
 [b'string']
 [b'here']], shape=(3, 1), dtype=string)


#Converting Numpy array to Tensor

In [1]:
import numpy as np

In [2]:
np_arr = np.array([2,6,4])
print(np_arr)

[2 6 4]


In [5]:
tensor_np = tf.convert_to_tensor(np_arr)
print(tensor_np)

tf.Tensor([2 6 4], shape=(3,), dtype=int64)


#Identity Tensor
- used to create identity tensor

In [10]:
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=4,
    batch_shape=[2,3], # used to create multi-dimensional tensors
    dtype=tf.dtypes.int32 # supported dtypes = int, float, bool, etc.,
    )
print(eye_tensor)

tf.Tensor(
[[[[1 0 0 0]
   [0 1 0 0]
   [0 0 1 0]]

  [[1 0 0 0]
   [0 1 0 0]
   [0 0 1 0]]

  [[1 0 0 0]
   [0 1 0 0]
   [0 0 1 0]]]


 [[[1 0 0 0]
   [0 1 0 0]
   [0 0 1 0]]

  [[1 0 0 0]
   [0 1 0 0]
   [0 0 1 0]]

  [[1 0 0 0]
   [0 1 0 0]
   [0 0 1 0]]]], shape=(2, 3, 3, 4), dtype=int32)


#Fill Tensor
- fills the tensor with value provided

In [15]:
fill_tf = tf.fill([2,5,4],10)
print(fill_tf)

tf.Tensor(
[[[10 10 10 10]
  [10 10 10 10]
  [10 10 10 10]
  [10 10 10 10]
  [10 10 10 10]]

 [[10 10 10 10]
  [10 10 10 10]
  [10 10 10 10]
  [10 10 10 10]
  [10 10 10 10]]], shape=(2, 5, 4), dtype=int32)


#Ones Tensor
- creates a tensor with value 1

In [17]:
ones_tensor = tf.ones([2,4,5], dtype = tf.dtypes.float16)
print(ones_tensor)

tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(2, 4, 5), dtype=float16)
